version: '3'
services:
  find-me-server:
    image: mvtthew/findme-server:0.40.1
    platform: linux/x86_64
    restart: always
    env_file: ./.env
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    depends_on:
      - find-me-db
  find-me-db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
    ports:
      - "${DB_PORT_DOCKER_LISTEN}:3306"
    volumes:
      - database:/var/lib/mysql
volumes:
  database:
