version: '3'
services:
  app:
    image: mvtthew/findme-server:0.38.1
    restart: always
    env_file: ./.env
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    ports:
      - 27027:27017
    volumes:
      - db:/data/db
volumes:
 db:
