module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverageFrom: [
    './src/**',
    '!**/node_modules/**',
    '!**/config/**',
    '!**/*.module.ts',
    '!**/*.schema.ts',
    '!./src/App.ts',
    '!./src/main.ts',
    '!./src/constants/**',
    '!./src/config/**',
    '!./src/tests/**',
  ],
  moduleNameMapper: { "@src/(.*)": "<rootDir>/src/$1" },
  coverageReporters: [ 'text', 'text-summary', 'html', 'clover' ],
  setupFilesAfterEnv: [ './src/tests/setupTests.ts' ],
  testRegex: '.*\\.spec\\.ts$',
  transform: { '^.+\\.(t|j)s$': 'ts-jest' },
};
