version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
          test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build app
          command: yarn build

workflows:
  findme-ci:
    jobs:
      - test
      - build
